// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;
import 'dart:io';

/// Bindings for `src/openlist_background_service.h`.
///
/// Regenerate bindings with `flutter pub run ffigen --config ffigen.yaml`.
///
class AListMobileServiceBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AListMobileServiceBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AListMobileServiceBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      lookup)
      : _lookup = lookup;

  void Run() {
    return _Run();
  }

  late final _RunPtr = (Platform.isMacOS || Platform.isIOS)?_lookup<ffi.NativeFunction<ffi.Void Function()>>('MobileRun'):
  (Platform.isAndroid?_lookup<ffi.NativeFunction<ffi.Void Function()>>('Java_mobile_Mobile_run'):_lookup<ffi.NativeFunction<ffi.Void Function()>>('Run'));
  late final _Run = _RunPtr.asFunction<void Function()>();

//   Java_mobile_Mobile_setConfigData
}
